# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Awp54SbEDPcfvH7LmVXjw8ncS4G0NAmBsnGkdsebsNZgyD+H3k9Mhligt3rgx9Aa51LfBZKpqByEpQFo/iyC1UFn7erbnHY25Q5CroEgX/zVxFB7NJWH1zYbg0kZFbaf3annkEZZRb4zpLYI7IcCfaev8eRHFpIwrLOygxion2Cpa0MhlfNG122w5Kdhmq3Kx/HN4b3RkhdF3ouhbN7HsftipCwjs+YcnAoBBErJQNMAFnhGg2880P6VJi5rzz6D8i9pIhYc4M9QxKGKRMKuVl0tb4X+TJpFDWO/Wf8fRffLrZoiVOCR4/OtJMZdhebB0id0S+6dxHjXf8RhKI2PuRrti+8gRDBAABcm4Oz6RKuAqjLcwMFZ+1slYlF152GkOSZvJ8YUdIptSUPvXKYj+JSTBx3jueAYeGUvJrSahdgTKNOBXtwhwmUIAN8WTqAmjigCXFXVTYMOx0WzAW1QqlJD29zKTyrNq0FhYOeVSqHCJZ9F3AonjjwWZvwLqLkYBPsPQrnohlW3KdN3jWhRbd0M6jyoAGodtTcI4aw5BFOqxYLqa3c33iDpbyMYN+MSeQkh54zfAbFN4FxLtxizjGuNKNlQh/yuYaFSWBjWMy2Kb7dQm21KJJfyJMLPbW7Cm0lD6gzQnqRVVwA/c8J7eqEjr6V21Xjx3URLiemCZQs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
