travis:
  secure:
    BINSTAR_TOKEN: jWYwbMVWxdKGygoqaLfUR/A1+sNyzD3XddaryFDl6p5i3M6LPaoAAKG0xG+66xsgu3IeeXQwQPzVV6JamW5l+uBEmsycyIIdht96pm+/ne9s60Ft1CbBNHqRuldMvcl3Xx7MatMhsEcNRieKkDUfgbM4Dwki73M44xKPYt1naJx8QP/yrCr5YN75NUEjc/pyoNxmjAOVq6OcyquOjvWDwGXh6neax8M09rTZCqGDhMkPU3NIGhrTJgAOgurGMuZxg3TceRqGwuRr17qMFyN5JrJQkUUbXqOrjtb7KF8tNt3KJTo0PIEiEpIdJCzUggg4Q+v9EgZTkFuVUgY+QhNHybUhc96ksCcNkEb86hUHN7U9xRdAAfi7Cl8B3vxpMyui/us630UoxKs6vPT8c8PikiVkeeL+NbpMYd8xHTsj4C8bcnpbHoDnIBQGLA2Xsf4kNXsKEvHJMJbGyivPVbD4eMx9PtAhn2WnDBVY7qXKlyS9yp+fEGXNe6vcpz4IZkmeX3qmmq+e2RiUTsdUq0K6CpSqe6M0d3JS7R11bz069WDVlSF1UDc4Ja9bKoQ5g2jaQaMFj2H+SY6rqq2p3cZKVf9B+FyRzxXA4bv3udEUFDo/vBelUa1YVo30XK63Gt5HN4i7YZrU5NVjatfLjE0rv51TF7uJE1oXupedXz3RqJU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
