travis:
  secure:
    BINSTAR_TOKEN: Awp54SbEDPcfvH7LmVXjw8ncS4G0NAmBsnGkdsebsNZgyD+H3k9Mhligt3rgx9Aa51LfBZKpqByEpQFo/iyC1UFn7erbnHY25Q5CroEgX/zVxFB7NJWH1zYbg0kZFbaf3annkEZZRb4zpLYI7IcCfaev8eRHFpIwrLOygxion2Cpa0MhlfNG122w5Kdhmq3Kx/HN4b3RkhdF3ouhbN7HsftipCwjs+YcnAoBBErJQNMAFnhGg2880P6VJi5rzz6D8i9pIhYc4M9QxKGKRMKuVl0tb4X+TJpFDWO/Wf8fRffLrZoiVOCR4/OtJMZdhebB0id0S+6dxHjXf8RhKI2PuRrti+8gRDBAABcm4Oz6RKuAqjLcwMFZ+1slYlF152GkOSZvJ8YUdIptSUPvXKYj+JSTBx3jueAYeGUvJrSahdgTKNOBXtwhwmUIAN8WTqAmjigCXFXVTYMOx0WzAW1QqlJD29zKTyrNq0FhYOeVSqHCJZ9F3AonjjwWZvwLqLkYBPsPQrnohlW3KdN3jWhRbd0M6jyoAGodtTcI4aw5BFOqxYLqa3c33iDpbyMYN+MSeQkh54zfAbFN4FxLtxizjGuNKNlQh/yuYaFSWBjWMy2Kb7dQm21KJJfyJMLPbW7Cm0lD6gzQnqRVVwA/c8J7eqEjr6V21Xjx3URLiemCZQs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
