travis:
  secure:
    BINSTAR_TOKEN: du3zsalKyShEBpNLxsX9kuWcif1yPANt54vawct3UnqFtTixGoiq3P3B1eCAQs0nCX7t375kc893NumIZRxac4n4vH/5E/n5xidU6Cr/2GN0rKCWn7M0rp+svs89S1ym88rrVATV2xBiLPA0utcWUJDm/CJzz/3UdzJt3QlTqNKBowIxLenAv+09K3icn7iF2H2GCMit5hKMvlRBdekg68XhzeLfioMqyqOnruiEmvPxnfs/bMGm7ZvEVwMJ0cV0a+2+kyVZPbfp7F5dNgck+lSuNP8dFwqSA0gTBKhyRgp3AR1DhEhOK7YPmtuWbc7D2hgPbasT7Otbfg9WRgcHTGaae4TmqqVcqn0QWZGXNjyg2YfNaaWDK7EglU+ccjUL5l1AX0EF0QZlJzXyuEBWyhVW91FkDGRWVyG4LopaTs+s7S1jZnMOqq6pNSsmpiLX4W7ooJzndKGCg4RKJhjT3cZJrHP5j/QqKrWb15d+WHi+qMHH/xKiVBqApr4grAr4cbhQlMrkzpUtiFst5usjYqR0AStf7tSb6KxsaEbPnYbYerrYZQSbotIlXoZ6+P0lwE48PLzGV5v231pk7gCrR2+oqBh7vN7edTqkY4O7+Acm5//S6nG8pc7JOfBsc397zN6v0A4p1+gJ7lthE217tFRNt5P+ZNCf2r6j0LAJHk0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
