travis:
  secure:
    BINSTAR_TOKEN: VA3ZVgX6NHtS+R8ABw7pgOpBDCW1fByEvaf1VjE6LGW05APydYzyPtZom1qw3Ea1T8XwHpD5GVF2F3Tt0WOTuei8iNHdUgHrEl1VGe7vaWzFMf1RqesDKrlkXkR/hblqvfpi3fT6XiE9vh77idxa6qQ8HGNt/VzKv4FeRD7POBC7/UvIZFQLkEGka4iKpbdgNRMaoEpox3ByjE59D3Ln6xV9bv4B7t78QwQ0qgyDSr2Cfmb9g8ENPgd1op7nRFi252aIaZV42SHDxhVWGGK145n7QlgmIUmBWSqLtXuSA9WSh0IXM3xeWNa1jQzmdveYg+sB7slIU3z2zsigpdY0nonC07ipaISq3aa9sy/n4F+A/3tNtFjSrPEk6pPNHCG+7+d2c9kaYixHna23qgdVpYSd0NBrkRFRg5YrCTUEVLkhEWnWylLw03VAV6N8JCnBd7IdwpiTCMX/UXUHhP/wvQnDR1X1rf3RVNmDSXxIv5/9wKVZKLmg2zyIFsIWCQNVC4GBDuoGiAWoqmwZb+xQB+hATAO+Gm41I+o+wyF+Xcj7h7oSAR26NzN+ssyPK8sNHwFu+g9F2xdqnKG+x14HeWp8Y19+1g6zjyUheoqkYWUpO+am5j8kHLhTfyQcWgCM9UUY2uD7IrBuLFu7oqT13rymkiy0pX5W5OJtYrZhg30=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
